/*
    Countries Alpha-3 codes:
    https://www.iban.com/country-codes
*/

import { Country } from "./types"

export enum CountryCode {
    AFGHANISTAN = "AFG",
    ALAND_ISLANDS = "ALA",
    ALBANIA = "ALB",
    ALGERIA = "DZA",
    AMERICAN_SAMOA = "ASM",
    ANDORRA = "AND",
    ANGOLA = "AGO",
    ANGUILLA = "AIA",
    ANTARCTICA = "ATA",
    ANTIGUA_AND_BARBUDA = "ATG",
    ARGENTINA = "ARG",
    ARMENIA = "ARM",
    ARUBA = "ABW",
    AUSTRALIA = "AUS",
    AUSTRIA = "AUT",
    AZERBAIJAN = "AZE",
    BAHAMAS = "BHS",
    BAHRAIN = "BHR",
    BANGLADESH = "BGD",
    BARBADOS = "BRB",
    BELARUS = "BLR",
    BELGIUM = "BEL",
    BELIZE = "BLZ",
    BENIN = "BEN",
    BERMUDA = "BMU",
    BHUTAN = "BTN",
    BOLIVIA = "BOL",
    BONAIRE = "BES",
    BOSNIA_AND_HERZEGOVINA = "BIH",
    BOTSWANA = "BWA",
    BOUVET_ISLAND = "BVT",
    BRAZIL = "BRA",
    BRITISH_INDIAN_OCEAN_TERRITORY = "IOT",
    BRUNEI_DARUSSALAM = "BRN",
    BULGARIA = "BGR",
    BURKINA_FASO = "BFA",
    BURUNDI = "BDI",
    CAMBODIA = "KHM",
    CAMEROON = "CMR",
    CANADA = "CAN",
    CAPE_VERDE = "CPV",
    CAYMAN_ISLANDS = "CYM",
    CENTRAL_AFRICAN_REPUBLIC = "CAF",
    KOSOVO = "CS-KM",
    CHAD = "TCD",
    CHILE = "CHL",
    CHINA = "CHN",
    CHRISTMAS_ISLAND = "CXR",
    COCOS_ISLANDS = "CCK",
    COLOMBIA = "COL",
    COMOROS = "COM",
    CONGO_KINSHASA = "COD",
    CONGO_BRAZZAVILLE = "COG",
    COOK_ISLANDS = "COK",
    COSTA_RICA = "CRI",
    COTE_D_IVOIRE = "CIV",
    CROATIA = "HRV",
    CUBA = "CUB",
    CURACAO = "CUW",
    CYPRUS = "CYP",
    CZECHIA = "CZE",
    DENMARK = "DNK",
    DJIBOUTI = "DJI",
    DOMINICA = "DMA",
    DOMINICAN_REPUBLIC = "DOM",
    ECUADOR = "ECU",
    EGYPT = "EGY",
    EL_SALVADOR = "SLV",
    EQUATORIAL_GUINEA = "GNQ",
    ERITREA = "ERI",
    ESTONIA = "EST",
    ETHIOPIA = "ETH",
    FALKLAND_ISLANDS = "FLK",
    FAROE_ISLANDS = "FRO",
    FIJI = "FJI",
    FINLAND = "FIN",
    FRANCE = "FRA",
    FRENCH_GUIANA = "GUF",
    FRENCH_POLYNESIA = "PYF",
    FRENCH_SOUTHERN_LANDS = "ATF",
    GABON = "GAB",
    GAMBIA = "GMB",
    GEORGIA = "GEO",
    GERMANY = "DEU",
    GHANA = "GHA",
    GIBRALTAR = "GIB",
    GREECE = "GRC",
    GREENLAND = "GRL",
    GRENADA = "GRD",
    GUADELOUPE = "GLP",
    GUAM = "GUM",
    GUATEMALA = "GTM",
    GUERNSEY = "GGY",
    GUINEA = "GIN",
    GUINEA_BISSAU = "GNB",
    GUYANA = "GUY",
    HAITI = "HTI",
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = "HMD",
    VATICAN = "VAT",
    HONDURAS = "HND",
    HONG_KONG = "HKG",
    HUNGARY = "HUN",
    ICELAND = "ISL",
    INDIA = "IND",
    INDONESIA = "IDN",
    IRAN = "IRN",
    IRAQ = "IRQ",
    IRELAND = "IRL",
    ISLE_OF_MAN = "IMN",
    ISRAEL = "ISR",
    ITALY = "ITA",
    JAMAICA = "JAM",
    JAPAN = "JPN",
    JERSEY = "JEY",
    JORDAN = "JOR",
    KAZAKHSTAN = "KAZ",
    KENYA = "KEN",
    KIRIBATI = "KIR",
    NORTH_KOREA = "PRK",
    SOUTH_KOREA = "KOR",
    KUWAIT = "KWT",
    KYRGYZSTAN = "KGZ",
    LAOS = "LAO",
    LATVIA = "LVA",
    LEBANON = "LBN",
    LESOTHO = "LSO",
    LIBERIA = "LBR",
    LIBYA = "LBY",
    LIECHTENSTEIN = "LIE",
    LITHUANIA = "LTU",
    LUXEMBOURG = "LUX",
    MACAO = "MAC",
    MACEDONIA = "MKD",
    MADAGASCAR = "MDG",
    MALAWI = "MWI",
    MALAYSIA = "MYS",
    MALDIVES = "MDV",
    MALI = "MLI",
    MALTA = "MLT",
    MARSHALL_ISLANDS = "MHL",
    MARTINIQUE = "MTQ",
    MAURITANIA = "MRT",
    MAURITIUS = "MUS",
    MAYOTTE = "MYT",
    MEXICO = "MEX",
    MICRONESIA = "FSM",
    MOLDOVA = "MDA",
    MONACO = "MCO",
    MONGOLIA = "MNG",
    MONTENEGRO = "MNE",
    MONTSERRAT = "MSR",
    MOROCCO = "MAR",
    MOZAMBIQUE = "MOZ",
    MYANMAR = "MMR",
    NAMIBIA = "NAM",
    NAURU = "NRU",
    NEPAL = "NPL",
    NETHERLANDS = "NLD",
    NEW_CALEDONIA = "NCL",
    NEW_ZEALAND = "NZL",
    NICARAGUA = "NIC",
    NIGER = "NER",
    NIGERIA = "NGA",
    NIUE = "NIU",
    NORFOLK_ISLAND = "NFK",
    NORTHERN_MARIANA_ISLANDS = "MNP",
    NORWAY = "NOR",
    OMAN = "OMN",
    PAKISTAN = "PAK",
    PALAU = "PLW",
    PALESTINE = "PSE",
    PANAMA = "PAN",
    PAPUA_NEW_GUINEA = "PNG",
    PARAGUAY = "PRY",
    PERU = "PER",
    PHILIPPINES = "PHL",
    PITCAIRN = "PCN",
    POLAND = "POL",
    PORTUGAL = "PRT",
    PUERTO_RICO = "PRI",
    QATAR = "QAT",
    RÉUNION = "REU",
    ROMANIA = "ROU",
    RUSSIA = "RUS",
    RWANDA = "RWA",
    SAINT_BARTHELEMY = "BLM",
    SAINT_HELENA = "SHN",
    SAINT_KITTS_AND_NEVIS = "KNA",
    SAINT_LUCIA = "LCA",
    SAINT_MARTIN = "MAF",
    SAINT_PIERRE_AND_MIQUELON = "SPM",
    SAINT_VINCENT_AND_THE_GRENADINES = "VCT",
    SAMOA = "WSM",
    SAN_MARINO = "SMR",
    SAO_TOME_AND_PRINCIPE = "STP",
    SAUDI_ARABIA = "SAU",
    SENEGAL = "SEN",
    SERBIA = "SRB",
    SEYCHELLES = "SYC",
    SIERRA_LEONE = "SLE",
    SINGAPORE = "SGP",
    SINT_MAARTEN = "SXM",
    SLOVAKIA = "SVK",
    SLOVENIA = "SVN",
    SOLOMON_ISLANDS = "SLB",
    SOMALIA = "SOM",
    SOUTH_AFRICA = "ZAF",
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "SGS",
    SOUTH_SUDAN = "SSD",
    SPAIN = "ESP",
    SRI_LANKA = "LKA",
    SUDAN = "SDN",
    SURINAME = "SUR",
    SVALBARD_AND_JAN_MAYEN = "SJM",
    ESWATINI = "SWZ",
    SWEDEN = "SWE",
    SWITZERLAND = "CHE",
    SYRIA = "SYR",
    TAIWAN = "TWN",
    TAJIKISTAN = "TJK",
    TANZANIA = "TZA",
    THAILAND = "THA",
    TIMOR_LESTE = "TLS",
    TOGO = "TGO",
    TOKELAU = "TKL",
    TONGA = "TON",
    TRINIDAD_AND_TOBAGO = "TTO",
    TUNISIA = "TUN",
    TURKEY = "TUR",
    TURKMENISTAN = "TKM",
    TURKS_AND_CAICOS_ISLANDS = "TCA",
    TUVALU = "TUV",
    UGANDA = "UGA",
    UKRAINE = "UKR",
    UNITED_ARAB_EMIRATES = "ARE",
    UNITED_KINGDOM = "GBR",
    UNITED_STATES = "USA",
    UNITED_STATES_MINOR_OUTLYING_ISLANDS = "UMI",
    URUGUAY = "URY",
    UZBEKISTAN = "UZB",
    VANUATU = "VUT",
    VENEZUELA = "VEN",
    VIETNAM = "VNM",
    BRITISH_VIRGIN_ISLANDS = "VGB",
    VIRGIN_ISLANDS = "VIR",
    WALLIS_AND_FUTUNA = "WLF",
    WESTERN_SAHARA = "ESH",
    YEMEN = "YEM",
    ZAMBIA = "ZMB",
    ZIMBABWE = "ZWE",
}

const CC = CountryCode

export const countries: { [key in CountryCode]: Country } = {
    [CC.AFGHANISTAN]: { code: CC.AFGHANISTAN, name: "Afghanistan", flag: "🇦🇫" },
    [CC.ALAND_ISLANDS]: { code: CC.ALAND_ISLANDS, name: "Åland Islands", flag: "🇦🇽" },
    [CC.ALBANIA]: { code: CC.ALBANIA, name: "Albania", flag: "🇦🇱" },
    [CC.ALGERIA]: { code: CC.ALGERIA, name: "Algeria", flag: "🇩🇿" },
    [CC.AMERICAN_SAMOA]: { code: CC.AMERICAN_SAMOA, name: "American Samoa", flag: "🇦🇸" },
    [CC.ANDORRA]: { code: CC.ANDORRA, name: "Andorra", flag: "🇦🇩" },
    [CC.ANGOLA]: { code: CC.ANGOLA, name: "Angola", flag: "🇦🇴" },
    [CC.ANGUILLA]: { code: CC.ANGUILLA, name: "Anguilla", flag: "🇦🇮" },
    [CC.ANTARCTICA]: { code: CC.ANTARCTICA, name: "Antarctica", flag: "🇦🇶" },
    [CC.ANTIGUA_AND_BARBUDA]: {
        code: CC.ANTIGUA_AND_BARBUDA,
        name: "Antigua and Barbuda",
        flag: "🇦🇬",
    },
    [CC.ARGENTINA]: { code: CC.ARGENTINA, name: "Argentina", flag: "🇦🇷" },
    [CC.ARMENIA]: { code: CC.ARMENIA, name: "Armenia", flag: "🇦🇲" },
    [CC.ARUBA]: { code: CC.ARUBA, name: "Aruba", flag: "🇦🇼" },
    [CC.AUSTRALIA]: { code: CC.AUSTRALIA, name: "Australia", flag: "🇦🇺" },
    [CC.AUSTRIA]: { code: CC.AUSTRIA, name: "Austria", flag: "🇦🇹" },
    [CC.AZERBAIJAN]: { code: CC.AZERBAIJAN, name: "Azerbaijan", flag: "🇦🇿" },
    [CC.BAHAMAS]: { code: CC.BAHAMAS, name: "Bahamas", flag: "🇧🇸" },
    [CC.BAHRAIN]: { code: CC.BAHRAIN, name: "Bahrain", flag: "🇧🇭" },
    [CC.BANGLADESH]: { code: CC.BANGLADESH, name: "Bangladesh", flag: "🇧🇩" },
    [CC.BARBADOS]: { code: CC.BARBADOS, name: "Barbados", flag: "🇧🇧" },
    [CC.BELARUS]: { code: CC.BELARUS, name: "Belarus", flag: "🇧🇾" },
    [CC.BELGIUM]: { code: CC.BELGIUM, name: "Belgium", flag: "🇧🇪" },
    [CC.BELIZE]: { code: CC.BELIZE, name: "Belize", flag: "🇧🇿" },
    [CC.BENIN]: { code: CC.BENIN, name: "Benin", flag: "🇧🇯" },
    [CC.BERMUDA]: { code: CC.BERMUDA, name: "Bermuda", flag: "🇧🇲" },
    [CC.BHUTAN]: { code: CC.BHUTAN, name: "Bhutan", flag: "🇧🇹" },
    [CC.BOLIVIA]: { code: CC.BOLIVIA, name: "Bolivia", flag: "🇧🇴" },
    [CC.BONAIRE]: { code: CC.BONAIRE, name: "Bonaire", flag: "🇧🇶" },
    [CC.BOSNIA_AND_HERZEGOVINA]: {
        code: CC.BOSNIA_AND_HERZEGOVINA,
        name: "Bosnia and Herzegovina",
        flag: "🇧🇦",
    },
    [CC.BOTSWANA]: { code: CC.BOTSWANA, name: "Botswana", flag: "🇧🇼" },
    [CC.BOUVET_ISLAND]: { code: CC.BOUVET_ISLAND, name: "Bouvet Island", flag: "🇧🇻" },
    [CC.BRAZIL]: { code: CC.BRAZIL, name: "Brazil", flag: "🇧🇷" },
    [CC.BRITISH_INDIAN_OCEAN_TERRITORY]: {
        code: CC.BRITISH_INDIAN_OCEAN_TERRITORY,
        name: "British Indian Ocean Territory",
        flag: "🇮🇴",
    },
    [CC.BRUNEI_DARUSSALAM]: { code: CC.BRUNEI_DARUSSALAM, name: "Brunei Darussalam", flag: "🇧🇳" },
    [CC.BULGARIA]: { code: CC.BULGARIA, name: "Bulgaria", flag: "🇧🇬" },
    [CC.BURKINA_FASO]: { code: CC.BURKINA_FASO, name: "Burkina Faso", flag: "🇧🇫" },
    [CC.BURUNDI]: { code: CC.BURUNDI, name: "Burundi", flag: "🇧🇮" },
    [CC.CAMBODIA]: { code: CC.CAMBODIA, name: "Cambodia", flag: "🇰🇭" },
    [CC.CAMEROON]: { code: CC.CAMEROON, name: "Cameroon", flag: "🇨🇲" },
    [CC.CANADA]: { code: CC.CANADA, name: "Canada", flag: "🇨🇦" },
    [CC.CAPE_VERDE]: { code: CC.CAPE_VERDE, name: "Cape Verde", flag: "🇨🇻" },
    [CC.CAYMAN_ISLANDS]: { code: CC.CAYMAN_ISLANDS, name: "Cayman Islands", flag: "🇰🇾" },
    [CC.CENTRAL_AFRICAN_REPUBLIC]: {
        code: CC.CENTRAL_AFRICAN_REPUBLIC,
        name: "Central African Republic",
        flag: "🇨🇫",
    },
    [CC.CHAD]: { code: CC.CHAD, name: "Chad", flag: "🇹🇩" },
    [CC.CHILE]: { code: CC.CHILE, name: "Chile", flag: "🇨🇱" },
    [CC.CHINA]: { code: CC.CHINA, name: "China", flag: "🇨🇳" },
    [CC.CHRISTMAS_ISLAND]: { code: CC.CHRISTMAS_ISLAND, name: "Christmas Island", flag: "🇨🇽" },
    [CC.COCOS_ISLANDS]: { code: CC.COCOS_ISLANDS, name: "Cocos (Keeling) Islands", flag: "🇨🇨" },
    [CC.COLOMBIA]: { code: CC.COLOMBIA, name: "Colombia", flag: "🇨🇴" },
    [CC.COMOROS]: { code: CC.COMOROS, name: "Comoros", flag: "🇰🇲" },
    [CC.CONGO_BRAZZAVILLE]: {
        code: CC.CONGO_BRAZZAVILLE,
        name: "Republic of the Congo",
        flag: "🇨🇬",
    },
    [CC.CONGO_KINSHASA]: {
        code: CC.CONGO_KINSHASA,
        name: "Democratic Republic of the Congo",
        flag: "🇨🇩",
    },
    [CC.COOK_ISLANDS]: { code: CC.COOK_ISLANDS, name: "Cook Islands", flag: "🇨🇰" },
    [CC.COSTA_RICA]: { code: CC.COSTA_RICA, name: "Costa Rica", flag: "🇨🇷" },
    [CC.COTE_D_IVOIRE]: { code: CC.COTE_D_IVOIRE, name: "Côte d'Ivoire", flag: "🇨🇮" },
    [CC.CROATIA]: { code: CC.CROATIA, name: "Croatia", flag: "🇭🇷" },
    [CC.CUBA]: { code: CC.CUBA, name: "Cuba", flag: "🇨🇺" },
    [CC.CURACAO]: { code: CC.CURACAO, name: "Curaçao", flag: "🇨🇼" },
    [CC.CYPRUS]: { code: CC.CYPRUS, name: "Cyprus", flag: "🇨🇾" },
    [CC.CZECHIA]: { code: CC.CZECHIA, name: "Czech Republic", flag: "🇨🇿" },
    [CC.DENMARK]: { code: CC.DENMARK, name: "Denmark", flag: "🇩🇰" },
    [CC.DJIBOUTI]: { code: CC.DJIBOUTI, name: "Djibouti", flag: "🇩🇯" },
    [CC.DOMINICA]: { code: CC.DOMINICA, name: "Dominica", flag: "🇩🇲" },
    [CC.DOMINICAN_REPUBLIC]: {
        code: CC.DOMINICAN_REPUBLIC,
        name: "Dominican Republic",
        flag: "🇩🇴",
    },
    [CC.ECUADOR]: { code: CC.ECUADOR, name: "Ecuador", flag: "🇪🇨" },
    [CC.EGYPT]: { code: CC.EGYPT, name: "Egypt", flag: "🇪🇬" },
    [CC.EL_SALVADOR]: { code: CC.EL_SALVADOR, name: "El Salvador", flag: "🇸🇻" },
    [CC.EQUATORIAL_GUINEA]: { code: CC.EQUATORIAL_GUINEA, name: "Equatorial Guinea", flag: "🇬🇶" },
    [CC.ERITREA]: { code: CC.ERITREA, name: "Eritrea", flag: "🇪🇷" },
    [CC.ESTONIA]: { code: CC.ESTONIA, name: "Estonia", flag: "🇪🇪" },
    [CC.ESWATINI]: { code: CC.ESWATINI, name: "Eswatini", flag: "🇸🇿" },
    [CC.ETHIOPIA]: { code: CC.ETHIOPIA, name: "Ethiopia", flag: "🇪🇹" },
    [CC.FALKLAND_ISLANDS]: {
        code: CC.FALKLAND_ISLANDS,
        name: "Falkland Islands (Malvinas)",
        flag: "🇫🇰",
    },
    [CC.FAROE_ISLANDS]: { code: CC.FAROE_ISLANDS, name: "Faroe Islands", flag: "🇫🇴" },
    [CC.FIJI]: { code: CC.FIJI, name: "Fiji", flag: "🇫🇯" },
    [CC.FINLAND]: { code: CC.FINLAND, name: "Finland", flag: "🇫🇮" },
    [CC.FRANCE]: { code: CC.FRANCE, name: "France", flag: "🇫🇷" },
    [CC.FRENCH_GUIANA]: { code: CC.FRENCH_GUIANA, name: "French Guiana", flag: "🇬🇫" },
    [CC.FRENCH_POLYNESIA]: { code: CC.FRENCH_POLYNESIA, name: "French Polynesia", flag: "🇵🇫" },
    [CC.FRENCH_SOUTHERN_LANDS]: {
        code: CC.FRENCH_SOUTHERN_LANDS,
        name: "French Southern and Antarctic Lands",
        flag: "🇹🇫",
    },
    [CC.GABON]: { code: CC.GABON, name: "Gabon", flag: "🇬🇦" },
    [CC.GAMBIA]: { code: CC.GAMBIA, name: "Gambia", flag: "🇬🇲" },
    [CC.GEORGIA]: { code: CC.GEORGIA, name: "Georgia", flag: "🇬🇪" },
    [CC.GERMANY]: { code: CC.GERMANY, name: "Germany", flag: "🇩🇪" },
    [CC.GHANA]: { code: CC.GHANA, name: "Ghana", flag: "🇬🇭" },
    [CC.GIBRALTAR]: { code: CC.GIBRALTAR, name: "Gibraltar", flag: "🇬🇮" },
    [CC.GREECE]: { code: CC.GREECE, name: "Greece", flag: "🇬🇷" },
    [CC.GREENLAND]: { code: CC.GREENLAND, name: "Greenland", flag: "🇬🇱" },
    [CC.GRENADA]: { code: CC.GRENADA, name: "Grenada", flag: "🇬🇩" },
    [CC.GUADELOUPE]: { code: CC.GUADELOUPE, name: "Guadeloupe", flag: "🇬🇵" },
    [CC.GUAM]: { code: CC.GUAM, name: "Guam", flag: "🇬🇺" },
    [CC.GUATEMALA]: { code: CC.GUATEMALA, name: "Guatemala", flag: "🇬🇹" },
    [CC.GUERNSEY]: { code: CC.GUERNSEY, name: "Guernsey", flag: "🇬🇬" },
    [CC.GUINEA]: { code: CC.GUINEA, name: "Guinea", flag: "🇬🇳" },
    [CC.GUINEA_BISSAU]: { code: CC.GUINEA_BISSAU, name: "Guinea-Bissau", flag: "🇬🇼" },
    [CC.GUYANA]: { code: CC.GUYANA, name: "Guyana", flag: "🇬🇾" },
    [CC.HAITI]: { code: CC.HAITI, name: "Haiti", flag: "🇭🇹" },
    [CC.HEARD_ISLAND_AND_MCDONALD_ISLANDS]: {
        code: CC.HEARD_ISLAND_AND_MCDONALD_ISLANDS,
        name: "Heard Island and McDonald Islands",
        flag: "🇭🇲",
    },
    [CC.VATICAN]: { code: CC.VATICAN, name: "Vatican", flag: "🇻🇦" },
    [CC.HONDURAS]: { code: CC.HONDURAS, name: "Honduras", flag: "🇭🇳" },
    [CC.HONG_KONG]: { code: CC.HONG_KONG, name: "Hong Kong", flag: "🇭🇰" },
    [CC.HUNGARY]: { code: CC.HUNGARY, name: "Hungary", flag: "🇭🇺" },
    [CC.ICELAND]: { code: CC.ICELAND, name: "Iceland", flag: "🇮🇸" },
    [CC.INDIA]: { code: CC.INDIA, name: "India", flag: "🇮🇳" },
    [CC.INDONESIA]: { code: CC.INDONESIA, name: "Indonesia", flag: "🇮🇩" },
    [CC.IRAN]: { code: CC.IRAN, name: "Iran", flag: "🇮🇷" },
    [CC.IRAQ]: { code: CC.IRAQ, name: "Iraq", flag: "🇮🇶" },
    [CC.IRELAND]: { code: CC.IRELAND, name: "Ireland", flag: "🇮🇪" },
    [CC.ISLE_OF_MAN]: { code: CC.ISLE_OF_MAN, name: "Isle of Man", flag: "🇮🇲" },
    [CC.ISRAEL]: { code: CC.ISRAEL, name: "Israel", flag: "🇮🇱" },
    [CC.ITALY]: { code: CC.ITALY, name: "Italy", flag: "🇮🇹" },
    [CC.JAMAICA]: { code: CC.JAMAICA, name: "Jamaica", flag: "🇯🇲" },
    [CC.JAPAN]: { code: CC.JAPAN, name: "Japan", flag: "🇯🇵" },
    [CC.JERSEY]: { code: CC.JERSEY, name: "Jersey", flag: "🇯🇪" },
    [CC.JORDAN]: { code: CC.JORDAN, name: "Jordan", flag: "🇯🇴" },
    [CC.KAZAKHSTAN]: { code: CC.KAZAKHSTAN, name: "Kazakhstan", flag: "🇰🇿" },
    [CC.KENYA]: { code: CC.KENYA, name: "Kenya", flag: "🇰🇪" },
    [CC.KIRIBATI]: { code: CC.KIRIBATI, name: "Kiribati", flag: "🇰🇮" },
    [CC.KOSOVO]: { code: CC.KOSOVO, name: "Kosovo", flag: "🇽🇰" },
    [CC.NORTH_KOREA]: { code: CC.NORTH_KOREA, name: "North Korea", flag: "🇰🇵" },
    [CC.SOUTH_KOREA]: { code: CC.SOUTH_KOREA, name: "South Korea", flag: "🇰🇷" },
    [CC.KUWAIT]: { code: CC.KUWAIT, name: "Kuwait", flag: "🇰🇼" },
    [CC.KYRGYZSTAN]: { code: CC.KYRGYZSTAN, name: "Kyrgyzstan", flag: "🇰🇬" },
    [CC.LAOS]: { code: CC.LAOS, name: "Laos", flag: "🇱🇦" },
    [CC.LATVIA]: { code: CC.LATVIA, name: "Latvia", flag: "🇱🇻" },
    [CC.LEBANON]: { code: CC.LEBANON, name: "Lebanon", flag: "🇱🇧" },
    [CC.LESOTHO]: { code: CC.LESOTHO, name: "Lesotho", flag: "🇱🇸" },
    [CC.LIBERIA]: { code: CC.LIBERIA, name: "Liberia", flag: "🇱🇷" },
    [CC.LIBYA]: { code: CC.LIBYA, name: "Libya", flag: "🇱🇾" },
    [CC.LIECHTENSTEIN]: { code: CC.LIECHTENSTEIN, name: "Liechtenstein", flag: "🇱🇮" },
    [CC.LITHUANIA]: { code: CC.LITHUANIA, name: "Lithuania", flag: "🇱🇹" },
    [CC.LUXEMBOURG]: { code: CC.LUXEMBOURG, name: "Luxembourg", flag: "🇱🇺" },
    [CC.MACAO]: { code: CC.MACAO, name: "Macao", flag: "🇲🇴" },
    [CC.MACEDONIA]: { code: CC.MACEDONIA, name: "North Macedonia", flag: "🇲🇰" },
    [CC.MADAGASCAR]: { code: CC.MADAGASCAR, name: "Madagascar", flag: "🇲🇬" },
    [CC.MALAWI]: { code: CC.MALAWI, name: "Malawi", flag: "🇲🇼" },
    [CC.MALAYSIA]: { code: CC.MALAYSIA, name: "Malaysia", flag: "🇲🇾" },
    [CC.MALDIVES]: { code: CC.MALDIVES, name: "Maldives", flag: "🇲🇻" },
    [CC.MALI]: { code: CC.MALI, name: "Mali", flag: "🇲🇱" },
    [CC.MALTA]: { code: CC.MALTA, name: "Malta", flag: "🇲🇹" },
    [CC.MARSHALL_ISLANDS]: { code: CC.MARSHALL_ISLANDS, name: "Marshall Islands", flag: "🇲🇭" },
    [CC.MARTINIQUE]: { code: CC.MARTINIQUE, name: "Martinique", flag: "🇲🇶" },
    [CC.MAURITANIA]: { code: CC.MAURITANIA, name: "Mauritania", flag: "🇲🇷" },
    [CC.MAURITIUS]: { code: CC.MAURITIUS, name: "Mauritius", flag: "🇲🇺" },
    [CC.MAYOTTE]: { code: CC.MAYOTTE, name: "Mayotte", flag: "🇾🇹" },
    [CC.MEXICO]: { code: CC.MEXICO, name: "Mexico", flag: "🇲🇽" },
    [CC.MICRONESIA]: { code: CC.MICRONESIA, name: "Micronesia", flag: "🇫🇲" },
    [CC.MOLDOVA]: { code: CC.MOLDOVA, name: "Moldova", flag: "🇲🇩" },
    [CC.MONACO]: { code: CC.MONACO, name: "Monaco", flag: "🇲🇨" },
    [CC.MONGOLIA]: { code: CC.MONGOLIA, name: "Mongolia", flag: "🇲🇳" },
    [CC.MONTENEGRO]: { code: CC.MONTENEGRO, name: "Montenegro", flag: "🇲🇪" },
    [CC.MONTSERRAT]: { code: CC.MONTSERRAT, name: "Montserrat", flag: "🇲🇸" },
    [CC.MOROCCO]: { code: CC.MOROCCO, name: "Morocco", flag: "🇲🇦" },
    [CC.MOZAMBIQUE]: { code: CC.MOZAMBIQUE, name: "Mozambique", flag: "🇲🇿" },
    [CC.MYANMAR]: { code: CC.MYANMAR, name: "Myanmar", flag: "🇲🇲" },
    [CC.NAMIBIA]: { code: CC.NAMIBIA, name: "Namibia", flag: "🇳🇦" },
    [CC.NAURU]: { code: CC.NAURU, name: "Nauru", flag: "🇳🇷" },
    [CC.NEPAL]: { code: CC.NEPAL, name: "Nepal", flag: "🇳🇵" },
    [CC.NETHERLANDS]: { code: CC.NETHERLANDS, name: "Netherlands", flag: "🇳🇱" },
    [CC.NEW_CALEDONIA]: { code: CC.NEW_CALEDONIA, name: "New Caledonia", flag: "🇳🇨" },
    [CC.NEW_ZEALAND]: { code: CC.NEW_ZEALAND, name: "New Zealand", flag: "🇳🇿" },
    [CC.NICARAGUA]: { code: CC.NICARAGUA, name: "Nicaragua", flag: "🇳🇮" },
    [CC.NIGER]: { code: CC.NIGER, name: "Niger", flag: "🇳🇪" },
    [CC.NIGERIA]: { code: CC.NIGERIA, name: "Nigeria", flag: "🇳🇬" },
    [CC.NIUE]: { code: CC.NIUE, name: "Niue", flag: "🇳🇺" },
    [CC.NORFOLK_ISLAND]: { code: CC.NORFOLK_ISLAND, name: "Norfolk Island", flag: "🇳🇫" },
    [CC.NORTHERN_MARIANA_ISLANDS]: {
        code: CC.NORTHERN_MARIANA_ISLANDS,
        name: "Northern Mariana Islands",
        flag: "🇲🇵",
    },
    [CC.NORWAY]: { code: CC.NORWAY, name: "Norway", flag: "🇳🇴" },
    [CC.OMAN]: { code: CC.OMAN, name: "Oman", flag: "🇴🇲" },
    [CC.PAKISTAN]: { code: CC.PAKISTAN, name: "Pakistan", flag: "🇵🇰" },
    [CC.PALAU]: { code: CC.PALAU, name: "Palau", flag: "🇵🇼" },
    [CC.PALESTINE]: { code: CC.PALESTINE, name: "Palestine", flag: "🇵🇸" },
    [CC.PANAMA]: { code: CC.PANAMA, name: "Panama", flag: "🇵🇦" },
    [CC.PAPUA_NEW_GUINEA]: { code: CC.PAPUA_NEW_GUINEA, name: "Papua New Guinea", flag: "🇵🇬" },
    [CC.PARAGUAY]: { code: CC.PARAGUAY, name: "Paraguay", flag: "🇵🇾" },
    [CC.PERU]: { code: CC.PERU, name: "Peru", flag: "🇵🇪" },
    [CC.PHILIPPINES]: { code: CC.PHILIPPINES, name: "Philippines", flag: "🇵🇭" },
    [CC.PITCAIRN]: { code: CC.PITCAIRN, name: "Pitcairn", flag: "🇵🇳" },
    [CC.POLAND]: { code: CC.POLAND, name: "Poland", flag: "🇵🇱" },
    [CC.PORTUGAL]: { code: CC.PORTUGAL, name: "Portugal", flag: "🇵🇹" },
    [CC.PUERTO_RICO]: { code: CC.PUERTO_RICO, name: "Puerto Rico", flag: "🇵🇷" },
    [CC.QATAR]: { code: CC.QATAR, name: "Qatar", flag: "🇶🇦" },
    [CC.RÉUNION]: { code: CC.RÉUNION, name: "Réunion", flag: "🇷🇪" },
    [CC.ROMANIA]: { code: CC.ROMANIA, name: "Romania", flag: "🇷🇴" },
    [CC.RUSSIA]: { code: CC.RUSSIA, name: "Russia", flag: "🇷🇺" },
    [CC.RWANDA]: { code: CC.RWANDA, name: "Rwanda", flag: "🇷🇼" },
    [CC.SAINT_BARTHELEMY]: { code: CC.SAINT_BARTHELEMY, name: "Saint Barthélemy", flag: "🇧🇱" },
    [CC.SAINT_HELENA]: {
        code: CC.SAINT_HELENA,
        name: "Saint Helena, Ascension and Tristan da Cunha",
        flag: "🇸🇭",
    },
    [CC.SAINT_KITTS_AND_NEVIS]: {
        code: CC.SAINT_KITTS_AND_NEVIS,
        name: "Saint Kitts and Nevis",
        flag: "🇰🇳",
    },
    [CC.SAINT_LUCIA]: { code: CC.SAINT_LUCIA, name: "Saint Lucia", flag: "🇱🇨" },
    [CC.SAINT_MARTIN]: { code: CC.SAINT_MARTIN, name: "Saint Martin (French part)", flag: "🇲🇫" },
    [CC.SAINT_PIERRE_AND_MIQUELON]: {
        code: CC.SAINT_PIERRE_AND_MIQUELON,
        name: "Saint Pierre and Miquelon",
        flag: "🇵🇲",
    },
    [CC.SAINT_VINCENT_AND_THE_GRENADINES]: {
        code: CC.SAINT_VINCENT_AND_THE_GRENADINES,
        name: "Saint Vincent and the Grenadines",
        flag: "🇻🇨",
    },
    [CC.SAMOA]: { code: CC.SAMOA, name: "Samoa", flag: "🇼🇸" },
    [CC.SAN_MARINO]: { code: CC.SAN_MARINO, name: "San Marino", flag: "🇸🇲" },
    [CC.SAO_TOME_AND_PRINCIPE]: {
        code: CC.SAO_TOME_AND_PRINCIPE,
        name: "Sao Tome and Principe",
        flag: "🇸🇹",
    },
    [CC.SAUDI_ARABIA]: { code: CC.SAUDI_ARABIA, name: "Saudi Arabia", flag: "🇸🇦" },
    [CC.SENEGAL]: { code: CC.SENEGAL, name: "Senegal", flag: "🇸🇳" },
    [CC.SERBIA]: { code: CC.SERBIA, name: "Serbia", flag: "🇷🇸" },
    [CC.SEYCHELLES]: { code: CC.SEYCHELLES, name: "Seychelles", flag: "🇸🇨" },
    [CC.SIERRA_LEONE]: { code: CC.SIERRA_LEONE, name: "Sierra Leone", flag: "🇸🇱" },
    [CC.SINGAPORE]: { code: CC.SINGAPORE, name: "Singapore", flag: "🇸🇬" },
    [CC.SINT_MAARTEN]: { code: CC.SINT_MAARTEN, name: "Sint Maarten (Dutch part)", flag: "🇸🇽" },
    [CC.SLOVAKIA]: { code: CC.SLOVAKIA, name: "Slovakia", flag: "🇸🇰" },
    [CC.SLOVENIA]: { code: CC.SLOVENIA, name: "Slovenia", flag: "🇸🇮" },
    [CC.SOLOMON_ISLANDS]: { code: CC.SOLOMON_ISLANDS, name: "Solomon Islands", flag: "🇸🇧" },
    [CC.SOMALIA]: { code: CC.SOMALIA, name: "Somalia", flag: "🇸🇴" },
    [CC.SOUTH_AFRICA]: { code: CC.SOUTH_AFRICA, name: "South Africa", flag: "🇿🇦" },
    [CC.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS]: {
        code: CC.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,
        name: "South Georgia and the South Sandwich Islands",
        flag: "🇬🇸",
    },
    [CC.SOUTH_SUDAN]: { code: CC.SOUTH_SUDAN, name: "South Sudan", flag: "🇸🇸" },
    [CC.SPAIN]: { code: CC.SPAIN, name: "Spain", flag: "🇪🇸" },
    [CC.SRI_LANKA]: { code: CC.SRI_LANKA, name: "Sri Lanka", flag: "🇱🇰" },
    [CC.SUDAN]: { code: CC.SUDAN, name: "Sudan", flag: "🇸🇩" },
    [CC.SURINAME]: { code: CC.SURINAME, name: "Suriname", flag: "🇸🇷" },
    [CC.SVALBARD_AND_JAN_MAYEN]: {
        code: CC.SVALBARD_AND_JAN_MAYEN,
        name: "Svalbard and Jan Mayen",
        flag: "🇸🇯",
    },
    [CC.SWEDEN]: { code: CC.SWEDEN, name: "Sweden", flag: "🇸🇪" },
    [CC.SWITZERLAND]: { code: CC.SWITZERLAND, name: "Switzerland", flag: "🇨🇭" },
    [CC.SYRIA]: { code: CC.SYRIA, name: "Syria", flag: "🇸🇾" },
    [CC.TAIWAN]: { code: CC.TAIWAN, name: "Taiwan", flag: "🇹🇼" },
    [CC.TAJIKISTAN]: { code: CC.TAJIKISTAN, name: "Tajikistan", flag: "🇹🇯" },
    [CC.TANZANIA]: { code: CC.TANZANIA, name: "Tanzania", flag: "🇹🇿" },
    [CC.THAILAND]: { code: CC.THAILAND, name: "Thailand", flag: "🇹🇭" },
    [CC.TIMOR_LESTE]: { code: CC.TIMOR_LESTE, name: "Timor-Leste", flag: "🇹🇱" },
    [CC.TOGO]: { code: CC.TOGO, name: "Togo", flag: "🇹🇬" },
    [CC.TOKELAU]: { code: CC.TOKELAU, name: "Tokelau", flag: "🇹🇰" },
    [CC.TONGA]: { code: CC.TONGA, name: "Tonga", flag: "🇹🇴" },
    [CC.TRINIDAD_AND_TOBAGO]: {
        code: CC.TRINIDAD_AND_TOBAGO,
        name: "Trinidad and Tobago",
        flag: "🇹🇹",
    },
    [CC.TUNISIA]: { code: CC.TUNISIA, name: "Tunisia", flag: "🇹🇳" },
    [CC.TURKEY]: { code: CC.TURKEY, name: "Turkey", flag: "🇹🇷" },
    [CC.TURKMENISTAN]: { code: CC.TURKMENISTAN, name: "Turkmenistan", flag: "🇹🇲" },
    [CC.TURKS_AND_CAICOS_ISLANDS]: {
        code: CC.TURKS_AND_CAICOS_ISLANDS,
        name: "Turks and Caicos Islands",
        flag: "🇹🇨",
    },
    [CC.TUVALU]: { code: CC.TUVALU, name: "Tuvalu", flag: "🇹🇻" },
    [CC.UGANDA]: { code: CC.UGANDA, name: "Uganda", flag: "🇺🇬" },
    [CC.UKRAINE]: { code: CC.UKRAINE, name: "Ukraine", flag: "🇺🇦" },
    [CC.UNITED_ARAB_EMIRATES]: {
        code: CC.UNITED_ARAB_EMIRATES,
        name: "United Arab Emirates",
        flag: "🇦🇪",
    },
    [CC.UNITED_KINGDOM]: { code: CC.UNITED_KINGDOM, name: "United Kingdom", flag: "🇬🇧" },
    [CC.UNITED_STATES]: { code: CC.UNITED_STATES, name: "United States", flag: "🇺🇸" },
    [CC.UNITED_STATES_MINOR_OUTLYING_ISLANDS]: {
        code: CC.UNITED_STATES_MINOR_OUTLYING_ISLANDS,
        name: "United States Minor Outlying Islands",
        flag: "🇺🇲",
    },
    [CC.URUGUAY]: { code: CC.URUGUAY, name: "Uruguay", flag: "🇺🇾" },
    [CC.UZBEKISTAN]: { code: CC.UZBEKISTAN, name: "Uzbekistan", flag: "🇺🇿" },
    [CC.VANUATU]: { code: CC.VANUATU, name: "Vanuatu", flag: "🇻🇺" },
    [CC.VENEZUELA]: { code: CC.VENEZUELA, name: "Venezuela", flag: "🇻🇪" },
    [CC.VIETNAM]: { code: CC.VIETNAM, name: "Vietnam", flag: "🇻🇳" },
    [CC.BRITISH_VIRGIN_ISLANDS]: {
        code: CC.BRITISH_VIRGIN_ISLANDS,
        name: "British Virgin Islands",
        flag: "🇻🇬",
    },
    [CC.VIRGIN_ISLANDS]: { code: CC.VIRGIN_ISLANDS, name: "U.S. Virgin Islands", flag: "🇻🇮" },
    [CC.WALLIS_AND_FUTUNA]: { code: CC.WALLIS_AND_FUTUNA, name: "Wallis and Futuna", flag: "🇼🇫" },
    [CC.WESTERN_SAHARA]: { code: CC.WESTERN_SAHARA, name: "Western Sahara", flag: "🇪🇭" },
    [CC.YEMEN]: { code: CC.YEMEN, name: "Yemen", flag: "🇾🇪" },
    [CC.ZAMBIA]: { code: CC.ZAMBIA, name: "Zambia", flag: "🇿🇲" },
    [CC.ZIMBABWE]: { code: CC.ZIMBABWE, name: "Zimbabwe", flag: "🇿🇼" },
} as const
