/*
    Countries Alpha-3 codes:
    https://www.iban.com/country-codes
*/

export const countries = {
    AFG: { code: "AFG", name: "Afghanistan" },
    ALA: { code: "ALA", name: "Åland Islands" },
    ALB: { code: "ALB", name: "Albania" },
    DZA: { code: "DZA", name: "Algeria" },
    ASM: { code: "ASM", name: "American Samoa" },
    AND: { code: "AND", name: "Andorra" },
    AGO: { code: "AGO", name: "Angola" },
    AIA: { code: "AIA", name: "Anguilla" },
    ATA: { code: "ATA", name: "Antarctica" },
    ATG: { code: "ATG", name: "Antigua and Barbuda" },
    ARG: { code: "ARG", name: "Argentina" },
    ARM: { code: "ARM", name: "Armenia" },
    ABW: { code: "ABW", name: "Aruba" },
    AUS: { code: "AUS", name: "Australia" },
    AUT: { code: "AUT", name: "Austria" },
    AZE: { code: "AZE", name: "Azerbaijan" },
    BHS: { code: "BHS", name: "Bahamas" },
    BHR: { code: "BHR", name: "Bahrain" },
    BGD: { code: "BGD", name: "Bangladesh" },
    BRB: { code: "BRB", name: "Barbados" },
    BLR: { code: "BLR", name: "Belarus" },
    BEL: { code: "BEL", name: "Belgium" },
    BLZ: { code: "BLZ", name: "Belize" },
    BEN: { code: "BEN", name: "Benin" },
    BMU: { code: "BMU", name: "Bermuda" },
    BTN: { code: "BTN", name: "Bhutan" },
    BOL: { code: "BOL", name: "Bolivia, Plurinational State of" },
    BES: { code: "BES", name: "Bonaire, Sint Eustatius and Saba" },
    BIH: { code: "BIH", name: "Bosnia and Herzegovina" },
    BWA: { code: "BWA", name: "Botswana" },
    BVT: { code: "BVT", name: "Bouvet Island" },
    BRA: { code: "BRA", name: "Brazil" },
    IOT: { code: "IOT", name: "British Indian Ocean Territory" },
    BRN: { code: "BRN", name: "Brunei Darussalam" },
    BGR: { code: "BGR", name: "Bulgaria" },
    BFA: { code: "BFA", name: "Burkina Faso" },
    BDI: { code: "BDI", name: "Burundi" },
    KHM: { code: "KHM", name: "Cambodia" },
    CMR: { code: "CMR", name: "Cameroon" },
    CAN: { code: "CAN", name: "Canada" },
    CPV: { code: "CPV", name: "Cape Verde" },
    CYM: { code: "CYM", name: "Cayman Islands" },
    CAF: { code: "CAF", name: "Central African Republic" },
    "CS-KM": { code: "CS-KM", name: "Kosovo" },
    TCD: { code: "TCD", name: "Chad" },
    CHL: { code: "CHL", name: "Chile" },
    CHN: { code: "CHN", name: "China" },
    CXR: { code: "CXR", name: "Christmas Island" },
    CCK: { code: "CCK", name: "Cocos (Keeling) Islands" },
    COL: { code: "COL", name: "Colombia" },
    COM: { code: "COM", name: "Comoros" },
    COG: { code: "COG", name: "Congo" },
    COD: { code: "COD", name: "Congo, the Democratic Republic of the" },
    COK: { code: "COK", name: "Cook Islands" },
    CRI: { code: "CRI", name: "Costa Rica" },
    CIV: { code: "CIV", name: "Côte d'Ivoire" },
    HRV: { code: "HRV", name: "Croatia" },
    CUB: { code: "CUB", name: "Cuba" },
    CUW: { code: "CUW", name: "Curaçao" },
    CYP: { code: "CYP", name: "Cyprus" },
    CZE: { code: "CZE", name: "Czech Republic" },
    DNK: { code: "DNK", name: "Denmark" },
    DJI: { code: "DJI", name: "Djibouti" },
    DMA: { code: "DMA", name: "Dominica" },
    DOM: { code: "DOM", name: "Dominican Republic" },
    ECU: { code: "ECU", name: "Ecuador" },
    EGY: { code: "EGY", name: "Egypt" },
    SLV: { code: "SLV", name: "El Salvador" },
    GNQ: { code: "GNQ", name: "Equatorial Guinea" },
    ERI: { code: "ERI", name: "Eritrea" },
    EST: { code: "EST", name: "Estonia" },
    ETH: { code: "ETH", name: "Ethiopia" },
    FLK: { code: "FLK", name: "Falkland Islands (Malvinas)" },
    FRO: { code: "FRO", name: "Faroe Islands" },
    FJI: { code: "FJI", name: "Fiji" },
    FIN: { code: "FIN", name: "Finland" },
    FRA: { code: "FRA", name: "France" },
    GUF: { code: "GUF", name: "French Guiana" },
    PYF: { code: "PYF", name: "French Polynesia" },
    ATF: { code: "ATF", name: "French Southern Territories" },
    GAB: { code: "GAB", name: "Gabon" },
    GMB: { code: "GMB", name: "Gambia" },
    GEO: { code: "GEO", name: "Georgia" },
    DEU: { code: "DEU", name: "Germany" },
    GHA: { code: "GHA", name: "Ghana" },
    GIB: { code: "GIB", name: "Gibraltar" },
    GRC: { code: "GRC", name: "Greece" },
    GRL: { code: "GRL", name: "Greenland" },
    GRD: { code: "GRD", name: "Grenada" },
    GLP: { code: "GLP", name: "Guadeloupe" },
    GUM: { code: "GUM", name: "Guam" },
    GTM: { code: "GTM", name: "Guatemala" },
    GGY: { code: "GGY", name: "Guernsey" },
    GIN: { code: "GIN", name: "Guinea" },
    GNB: { code: "GNB", name: "Guinea-Bissau" },
    GUY: { code: "GUY", name: "Guyana" },
    HTI: { code: "HTI", name: "Haiti" },
    HMD: { code: "HMD", name: "Heard Island and McDonald Islands" },
    VAT: { code: "VAT", name: "Holy See (Vatican City State)" },
    HND: { code: "HND", name: "Honduras" },
    HKG: { code: "HKG", name: "Hong Kong" },
    HUN: { code: "HUN", name: "Hungary" },
    ISL: { code: "ISL", name: "Iceland" },
    IND: { code: "IND", name: "India" },
    IDN: { code: "IDN", name: "Indonesia" },
    IRN: { code: "IRN", name: "Iran, Islamic Republic of" },
    IRQ: { code: "IRQ", name: "Iraq" },
    IRL: { code: "IRL", name: "Ireland" },
    IMN: { code: "IMN", name: "Isle of Man" },
    ISR: { code: "ISR", name: "Israel" },
    ITA: { code: "ITA", name: "Italy" },
    JAM: { code: "JAM", name: "Jamaica" },
    JPN: { code: "JPN", name: "Japan" },
    JEY: { code: "JEY", name: "Jersey" },
    JOR: { code: "JOR", name: "Jordan" },
    KAZ: { code: "KAZ", name: "Kazakhstan" },
    KEN: { code: "KEN", name: "Kenya" },
    KIR: { code: "KIR", name: "Kiribati" },
    PRK: { code: "PRK", name: "Korea, Democratic People's Republic of" },
    KOR: { code: "KOR", name: "Korea, Republic of" },
    KWT: { code: "KWT", name: "Kuwait" },
    KGZ: { code: "KGZ", name: "Kyrgyzstan" },
    LAO: { code: "LAO", name: "Lao People's Democratic Republic" },
    LVA: { code: "LVA", name: "Latvia" },
    LBN: { code: "LBN", name: "Lebanon" },
    LSO: { code: "LSO", name: "Lesotho" },
    LBR: { code: "LBR", name: "Liberia" },
    LBY: { code: "LBY", name: "Libya" },
    LIE: { code: "LIE", name: "Liechtenstein" },
    LTU: { code: "LTU", name: "Lithuania" },
    LUX: { code: "LUX", name: "Luxembourg" },
    MAC: { code: "MAC", name: "Macao" },
    MKD: { code: "MKD", name: "Macedonia, the former Yugoslav Republic of" },
    MDG: { code: "MDG", name: "Madagascar" },
    MWI: { code: "MWI", name: "Malawi" },
    MYS: { code: "MYS", name: "Malaysia" },
    MDV: { code: "MDV", name: "Maldives" },
    MLI: { code: "MLI", name: "Mali" },
    MLT: { code: "MLT", name: "Malta" },
    MHL: { code: "MHL", name: "Marshall Islands" },
    MTQ: { code: "MTQ", name: "Martinique" },
    MRT: { code: "MRT", name: "Mauritania" },
    MUS: { code: "MUS", name: "Mauritius" },
    MYT: { code: "MYT", name: "Mayotte" },
    MEX: { code: "MEX", name: "Mexico" },
    FSM: { code: "FSM", name: "Micronesia, Federated States of" },
    MDA: { code: "MDA", name: "Moldova, Republic of" },
    MCO: { code: "MCO", name: "Monaco" },
    MNG: { code: "MNG", name: "Mongolia" },
    MNE: { code: "MNE", name: "Montenegro" },
    MSR: { code: "MSR", name: "Montserrat" },
    MAR: { code: "MAR", name: "Morocco" },
    MOZ: { code: "MOZ", name: "Mozambique" },
    MMR: { code: "MMR", name: "Myanmar" },
    NAM: { code: "NAM", name: "Namibia" },
    NRU: { code: "NRU", name: "Nauru" },
    NPL: { code: "NPL", name: "Nepal" },
    NLD: { code: "NLD", name: "Netherlands" },
    NCL: { code: "NCL", name: "New Caledonia" },
    NZL: { code: "NZL", name: "New Zealand" },
    NIC: { code: "NIC", name: "Nicaragua" },
    NER: { code: "NER", name: "Niger" },
    NGA: { code: "NGA", name: "Nigeria" },
    NIU: { code: "NIU", name: "Niue" },
    NFK: { code: "NFK", name: "Norfolk Island" },
    MNP: { code: "MNP", name: "Northern Mariana Islands" },
    NOR: { code: "NOR", name: "Norway" },
    OMN: { code: "OMN", name: "Oman" },
    PAK: { code: "PAK", name: "Pakistan" },
    PLW: { code: "PLW", name: "Palau" },
    PSE: { code: "PSE", name: "Palestinian Territory, Occupied" },
    PAN: { code: "PAN", name: "Panama" },
    PNG: { code: "PNG", name: "Papua New Guinea" },
    PRY: { code: "PRY", name: "Paraguay" },
    PER: { code: "PER", name: "Peru" },
    PHL: { code: "PHL", name: "Philippines" },
    PCN: { code: "PCN", name: "Pitcairn" },
    POL: { code: "POL", name: "Poland" },
    PRT: { code: "PRT", name: "Portugal" },
    PRI: { code: "PRI", name: "Puerto Rico" },
    QAT: { code: "QAT", name: "Qatar" },
    REU: { code: "REU", name: "Réunion" },
    ROU: { code: "ROU", name: "Romania" },
    RUS: { code: "RUS", name: "Russian Federation" },
    RWA: { code: "RWA", name: "Rwanda" },
    BLM: { code: "BLM", name: "Saint Barthélemy" },
    SHN: { code: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha" },
    KNA: { code: "KNA", name: "Saint Kitts and Nevis" },
    LCA: { code: "LCA", name: "Saint Lucia" },
    MAF: { code: "MAF", name: "Saint Martin (French part)" },
    SPM: { code: "SPM", name: "Saint Pierre and Miquelon" },
    VCT: { code: "VCT", name: "Saint Vincent and the Grenadines" },
    WSM: { code: "WSM", name: "Samoa" },
    SMR: { code: "SMR", name: "San Marino" },
    STP: { code: "STP", name: "Sao Tome and Principe" },
    SAU: { code: "SAU", name: "Saudi Arabia" },
    SEN: { code: "SEN", name: "Senegal" },
    SRB: { code: "SRB", name: "Serbia" },
    SYC: { code: "SYC", name: "Seychelles" },
    SLE: { code: "SLE", name: "Sierra Leone" },
    SGP: { code: "SGP", name: "Singapore" },
    SXM: { code: "SXM", name: "Sint Maarten (Dutch part)" },
    SVK: { code: "SVK", name: "Slovakia" },
    SVN: { code: "SVN", name: "Slovenia" },
    SLB: { code: "SLB", name: "Solomon Islands" },
    SOM: { code: "SOM", name: "Somalia" },
    ZAF: { code: "ZAF", name: "South Africa" },
    SGS: { code: "SGS", name: "South Georgia and the South Sandwich Islands" },
    SSD: { code: "SSD", name: "South Sudan" },
    ESP: { code: "ESP", name: "Spain" },
    LKA: { code: "LKA", name: "Sri Lanka" },
    SDN: { code: "SDN", name: "Sudan" },
    SUR: { code: "SUR", name: "Suriname" },
    SJM: { code: "SJM", name: "Svalbard and Jan Mayen" },
    SWZ: { code: "SWZ", name: "Swaziland" },
    SWE: { code: "SWE", name: "Sweden" },
    CHE: { code: "CHE", name: "Switzerland" },
    SYR: { code: "SYR", name: "Syrian Arab Republic" },
    TWN: { code: "TWN", name: "Taiwan, Province of China" },
    TJK: { code: "TJK", name: "Tajikistan" },
    TZA: { code: "TZA", name: "Tanzania, United Republic of" },
    THA: { code: "THA", name: "Thailand" },
    TLS: { code: "TLS", name: "Timor-Leste" },
    TGO: { code: "TGO", name: "Togo" },
    TKL: { code: "TKL", name: "Tokelau" },
    TON: { code: "TON", name: "Tonga" },
    TTO: { code: "TTO", name: "Trinidad and Tobago" },
    TUN: { code: "TUN", name: "Tunisia" },
    TUR: { code: "TUR", name: "Turkey" },
    TKM: { code: "TKM", name: "Turkmenistan" },
    TCA: { code: "TCA", name: "Turks and Caicos Islands" },
    TUV: { code: "TUV", name: "Tuvalu" },
    UGA: { code: "UGA", name: "Uganda" },
    UKR: { code: "UKR", name: "Ukraine" },
    ARE: { code: "ARE", name: "United Arab Emirates" },
    GBR: { code: "GBR", name: "United Kingdom" },
    USA: { code: "USA", name: "United States" },
    UMI: { code: "UMI", name: "United States Minor Outlying Islands" },
    URY: { code: "URY", name: "Uruguay" },
    UZB: { code: "UZB", name: "Uzbekistan" },
    VUT: { code: "VUT", name: "Vanuatu" },
    VEN: { code: "VEN", name: "Venezuela, Bolivarian Republic of" },
    VNM: { code: "VNM", name: "Viet Nam" },
    VGB: { code: "VGB", name: "Virgin Islands, British" },
    VIR: { code: "VIR", name: "Virgin Islands, U.S." },
    WLF: { code: "WLF", name: "Wallis and Futuna" },
    ESH: { code: "ESH", name: "Western Sahara" },
    YEM: { code: "YEM", name: "Yemen" },
    ZMB: { code: "ZMB", name: "Zambia" },
    ZWE: { code: "ZWE", name: "Zimbabwe" },
} as const
